# Generated by Django 2.2.1 on 2019-11-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraping', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='Emails',
            new_name='Email',
        ),
    ]
