# Generated by Django 2.2.1 on 2019-11-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraping', '0002_auto_20191107_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofileinfo',
            name='Email',
        ),
    ]
