# Generated by Django 2.2.1 on 2019-11-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_scraping', '0004_job_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sorted_Job_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=1000)),
            ],
        ),
    ]
